---
- hosts: all
  become: yes

  tasks:

    - name: Actualizacion de SO
      yum:
        name: '*'
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
    
    - name: Actualizacion de Cyberpanel
      ansible.builtin.shell: 'sh <(curl https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)'