---
- hosts: all
  become: yes

  tasks:

    - name: Install system updates for centos systems
      yum:
        name: '*'
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
